version: '3'
services:
  wordpress:
    depends_on:
      - db
    image: wordpress:latest # Change this to be version specific if desired
    restart: always
    volumes:
      - ./html:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: cCwh86ZvcfZ3RPb
    ports:
      - 8000:80 # Expose http and https
      - 443:443 # Port exposure is as follows first_port is the port that will run on your computer's localhost, second is the port exposed by the do$
    networks:
      - backend
  db:
    image: mysql:5.7
    restart: always
    volumes:
       - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: cCwh86ZvcfZ3RPb # Remove this for production
    networks:
      - backend
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: cCwh86ZvcfZ3RPb # Password here needs to match the mysql one above
      UPLOAD_LIMIT: 1000000000
    networks:
      - backend
networks:
  backend:
volumes:
  db_data: